 version: '3'
 services:
     mongo-seed:
      build: ./mongo-seed
      image: personalizedoncology/clinicalreportingdbrestapi_mongo-seed

     api:
      build: ./app
      image: personalizedoncology/clinicalreportingdbrestapi_api
      ports:
        - "5000:5000"
      volumes:
        - ./app:/app:rw
      depends_on:
        - mongo-seed